### ISSUE TITLE
Modellierung der Logik

### ISSUE THREAD

**Issue by seblin** [python-forum-de/pydesw-muehle#1]
Hier legen wir die Schnittstelle zur Spiellogik fest. Eine grafische Oberfläche ist hierbei noch nicht vorgesehen. Die Darstellung unseres Modells erfolgt als UML-Diagramm.

Wer hätte Interesse, sich an dieser Aufgabe zu beteiligen?

**Comment by sebastian2443** [comment]
Ich habe es mal versucht. Ist aber vermutlich unbrauchbar. 
Habe es einmal separat als PDF und einmal als Visio(2013) im ZIP hochgeladen.
Auf die schnelle fallen mir keine weiteren Funktionen für die Logik ein.

PS: Ist meine erster Kontakt mit UML / Klassendiagrammen.

[Muehle.pdf](https://github.com/python-forum-de/pydesw-muehle/files/789974/Muehle.pdf)
[Muehle.zip](https://github.com/python-forum-de/pydesw-muehle/files/789975/Muehle.zip)

**Comment by seblin** [comment]
Das ist doch schonmal ein guter Anfang. Visio Professional habe ich auch installiert, sodass ich es sogar bearbeiten könnte. Habe nur gerade nicht die Ruhe dafür. Ich schaue es mir noch heute Abend oder spätestens morgen genauer an.

**Comment by seblin** [comment]
Grundsätzlich kein schlechter Ansatz, jedoch sehr grob gehalten. Da stecken Sachen drin, die ich persönlich mit einer Codezeile abfrühstücken würde (z.B. die Feldbelegung). Dafür brauche ich die Schnittstelle nicht aufzublähen. Bei Rechteck wäre meine Frage, wozu es auf der Logikebene dafür eine eigene Klasse braucht? Felder ist zudem ein ungewöhnlicher Name für eine Klassse. Soll das dann eine abgeleitete Liste werden oder wie hattest du dir das gedacht? Welchen konkreten Mehrwert versprichst du dir von Rechteck und Felder?

**Comment by cpdef** [comment]
Und der Spieler gehört auch zur Logik oder? Ich denke das gui sollte nur der logik sagen, dass einer erstellt werden soll, etwa wie Logik.add_player(name,*args) o.ä.

**Comment by seblin** [comment]
Selbst das finde ich unnötig. An einem Spiel nehmen immer genau zwei Spieler teil. Möglicherweise ein menschlicher und ein Computergegner, aber die Anzahl steht fest. Die Zusammensetzung der Spieler könnte man daher direkt für die Initialisierung mitgeben, oder habe ich etwas übersehen?

**Comment by sebastian2443** [comment]
Die Anzahl der Spieler würde ich auch fest übergeben, genauso wie die benutzbaren Felder.
Habe mal ein neues Diagramm erstellt.

Mal von vorne. 
Der Spieler setzt/bewegt zuerst seine Steine. 
Logikklasse -> check_player_move: Ist das selektierte Feld besetzt?
Hat der Spieler ein Feld/Spielstein selektiert? (Oder macht das die GUI?)
(Bis zum 9. Zug muss immer nur das Feld selektiert werden, auf den ein Spielstein gesetzt wird)
(Ab dem 10. Zug müssen zwei Felder selektiert werden: von -> nach)

Falls ja, dann kann der Spielstein gesetzt werden (set_neighbor), ansonsten neue Auswahl.

Zum Schluss muss geprüft werden ob dabei eine Mühle entstanden ist.
Logikklasse -> is_mill:
Hier hätte ich die Idee eine JSON Datei zu erstellen um festzulegen welches Feld welche Nachbarn hat:
{   
    "A1" : {  "neighbor": { "up": "", "down": "A4", "right": "A2", "left": ""] },
    "A2" : {   "neighbor": { "up": "", "down": "M1", "right": "A3", "left": "A1"}, ...
}
Die Funktion is_mill von Logik nimmt dann beispielsweise "A2" (Spielsteinkoordinate) entgegen
und prüft die Nachbarn auf den gleichen Eigentümer.
Habe dazu mal ein Ablaufdiagramm erstellt.
[Nachbar_Ablauf.pdf](https://github.com/python-forum-de/pydesw-muehle/files/798863/Nachbar_Ablauf.pdf)

Wenn eine Mühle vorhanden ist, darf der Spieler einen Stein löschen.
Hier muss geprüft werden, ob es nicht der eigene Stein ist und das ausgewählte Feld nicht Teil
einer Mühle ist. (Auch testen, ob es überhaupt möglich ist einen Stein zu löschen? Sollte immer möglich sein, oder?)

Wenn tatsächlich ein Stein gelöscht wird, sollte geprüft werden ob das Spiel zu ende ist.
Logik -> game_is_over
Damit wäre der Ablauf eines Zuges abgeschlossen und der nächste Spieler an der Reihe.
Solange bis ein Spieler keine Steine mehr hat.

V2: [Muehle.zip](https://github.com/python-forum-de/pydesw-muehle/files/798862/Muehle.zip)
[Muehle.pdf](https://github.com/python-forum-de/pydesw-muehle/files/798864/Muehle.pdf)

**Comment by seblin** [comment]
Wobei ich das mit der JSON Datei etwas kompliziert finde. Wir brauchen ja nur eine generische Funktion, die für eine gegebene Position alle Nachbarpositionen ermittelt (z. B. Rückgabe als Set). Dann müsste man in den Bereichen, wo ein gültiger Zug geprüft werden soll, bloß zuerst schauen, ob die angegebene Position bei den Nachbarn dabei ist und andernfalls direkt meckern. Danach dann - wie vorgeschlagen - mittels is_mill() ermitteln, ob sich eine Mühle ergeben hat und in Abhängigkeit davon den Spieler zum Entfernen eines gegnerischen Steins auffordern. Beim gewünschten Entfernen auch wieder mit is_mill() prüfen, ob der gegnerische Stein geschützt ist und der Spieler somit eine neue Auswahl treffen muss.

Übrigens, anstelle eines Konzeptes von Eigentümern würde ich ganz einfach mit Farben (schwarz oder weiß) arbeiten. Sofern es darum geht, den Spieler mit seinem Namen anzusprechen, dann würde ich die Übersetzung von der Farbe zum Namen auf einer höheren Ebene vornehmen. Ist aber vielleicht auch Geschmackssache, wie man's letztlich machen möchte.

**Comment by Marrin** [comment]
@seblin @sebastian2443 Zum Diagramm (erste Fassung): `Felder` sollte wahrscheinlich `Feld` heissen und den Inhalt eines Feldes modellieren‽ In der Planungsphase kann es IMHO Sinn machen das als Klassen darzustellen. Wenn man dann feststellt, das `Rechteck` durch eine Liste abgedeckt werden kann, und man für `Feld` auch einfach den `Spieler` oder `None` verwenden kann, ist das in der Implementierung ja okay, wenn man dort dann für `Spielfeld.spieldfeld` (oder `Spielfeld.rechtecke`) einfach eine 2D-Liste mit `None`/`Spieler`-Exemplaren hat.

Wobei mir gerade auffällt, dass das alles deutsche Bezeichner sind.  Soll das Programm dann auch tatsächlich in Deutsch programmiert werden?

**Comment by seblin** [comment]
Auch ich würde es gut finden, wenn wir die abschließende Definition der Schnittstelle in Englisch halten könnten. Als Deadline schlage ich übernächsten Montag (6. März) vor. Ein paar Tage zum Diskutieren haben wir dann noch.  Etwa ab Mitte nächster Woche sollten wir dann wirklich konkret werden.

Übrigens: [PlantUML](https://en.wikipedia.org/wiki/PlantUML) wurde ja schon im Forum als eine Möglichkeit zur Modellierung vorgeschlagen. Es basiert auf Defintionen mittels einer Textdatei. Ich werde mich damit heute intensiver auseinandersetzen. Mal sehen, ob ich brauchbare Ergebnisse damit hinbekomme...

**Comment by seblin** [comment]
Hab mit PlantUML jetzt auch mal was gebastelt:

![muehle.png](https://cloud.githubusercontent.com/assets/621748/23334682/41d5e1ba-fba4-11e6-9722-4dfd84f5ab7e.png)

**Comment by seblin** [comment]
Etwas Feedback wäre schön. Entspricht das euren Vorstellungen? Habt ihr komplett andere Ideen? @sebastian2443 was sagst du dazu? Ich habe einige Ideen von dir übernommen. Hast du Lust, noch eine Variante zu basteln? Falls du auch mit PlantUML arbeiten möchtest, [hier](http://pastebin.com/3uE4NUMq) wäre der Quelltext. Was ich noch etwas vage finde, ist der Inhalt von do_next_move(). Vielleicht sollten wir hier noch etwas ins Detail gehen...

**Comment by sebastian2443** [comment]
Kam die Woche leider gar nicht dazu das Projekt weiter zu verfolgen und nächste Woche habe ich ein Seminar.
Eine weitere Variante mit PlantUML kann ich also wenn dann erst in zwei Wochen vorstellen. 

get_neighbors übernimmt dann die Logik dafür, wer wen als Nachbarn hat?
Denn Field kennt seine Nachbarn ja nicht..

Brauchen wir eine Funktion die uns ein Bool-Value liefert, ob der Zug auf ein Feld möglich ist?
Sowas wie is_movable(field) -> bool
Dadurch kann dann die GUI direkt daraufzugreifen und anzeigen ob der Zug möglich wäre oder nicht. 

Fürs Board wäre auch noch wichtig die Spielersteine zu selektieren. Keine Spielsteine mehr -> Spiel vorbei: game_finisch() -> bool

Ich hätte gerne auch soetwas wie eine Art Steuerung für den Ablauf einer Runde.
Arbeit = ['Spielstein bewegen']
while Arbeit:
    ... spielstein bewegt -> Mühle entstanden -> Arbeit.append('Gegnerischen Spielstein löschen')
...
while Arbeit:
    ... gegnerischen Spielstein gelöscht ... -> check_ob_game_finisch -> Runde beendet / Spiel vorbei

Oder wäre sowas zu viel?

(Den Quellcode auf Pastbin kann ich wegen den Restriktionen auf Arbeit nicht anschauen)

**Comment by seblin** [comment]
Das

**Comment by seblin** [comment]
Das Feld kennt seine Nachbarn nicht, aber das Brett kann die Nachbarn für ein Feld ermitteln. So hatte ich das gedacht.

**Comment by seblin** [comment]
@sebastian2443:
Kein Problem, wenn dein Kopf gerade mit anderen Dingen beschäftigt ist... ;)

Wäre jedenfalls schön, wenn du weiterhin am Ball bleibst (sobald sich wieder die Möglichkeit bietet). Ich möchte hier ungern den Alleinunterhalter spielen. Denn das ist wohl kaum die Intention hinter einem gemeinsamen Softwareprojekt.

(Das Schließen des Issues war versehentlich, weil man Handy manchmal spinnt. Der soll sinnigerweise erst dann geschlossen werden, wenn wir das Design der API abgeschlossen haben.)

**Comment by sebastian2443** [comment]
Ich konnte mir PlantUML noch nicht installieren. Ein weiteres UML Diagramm brauchen wir glaube auch gar nicht. 

Dass Das Board die Nachbarn der Felder ermittelt, finde ich jetzt auch besser.
Übernimmt eigentlich die GUI dann den Spielablauf? Irgendwo muss ja der Check hin,
ob ein Spieler das Spiel gewonnen hat?!

Ich würde übrigens move_piece und set_piece zusammenziehen. 
`move_piece(nach_feld, von_feld=None)`
eine Parameterübergabe ist 'setzen', zwei wären eine 'von-nach' Bewegung.
Return Value von move_piece() ist dann boolean, dadurch brauchen wir kein check_move(). 

Ansonsten ist denke ich soweit alles abgedeckt.

**Comment by seblin** [comment]
Den Check, ob ein Spiel gewonnen wurde, könnte man indirekt auf den Spieler verlagern: Es würde  do_next_move() eine Exception liefern, wenn kein Spielzug mehr möglich ist. Das lässt dann darauf schließen, dass derjenige Spieler verloren und somit der andere gewonnen hat.

Mit move_piece() können wir gerne so machen. Anstatt eines boolschen Wertes würde ich eher zu einer Exception tendieren, wenn ein Zug nicht möglich ist. Die Spieler würde dann in einer Schleife so oft move_piece() aufrufen bis der Spielzug sozusagen von der Logik angenommen wird. In den meisten Fällen wäre das natürlich ein einziger Iterationsschritt in der Schleife, weil meistens der erste Versuch gelingen wird.

Gibt's noch weitere Anmerkungen? Sonst würde ich spätestens bis Samstag einen finalen Vorschlag (wahrscheinlich wieder mit PlantUML) vorlegen, der dann noch "abgenickt" werden müsste. Dann können wir den Issue zum Ende der Woche als gelöst zumachen und uns der Programmierung zuwenden.

**Comment by sebastian2443** [comment]
Von mir keine weiteren Anmerkungen. Dann kannst du den finalen Vorschlag gerne vorlegen. 
War es das dann mit der Logik? Müssen wir kein Konzept für die GUI erstellen?

**Comment by seblin** [comment]
Hier nun mein finaler Vorschlag:
![muehle](https://user-images.githubusercontent.com/621748/34824475-df6fa156-f6ce-11e7-8199-704a0c16ff4d.png)
Gibt es dazu noch Fragen oder ist das so in Ordnung und sollen wir als nächstes zum Issue #2 übergehen?

**Comment by sebastian2443** [comment]
Irgendwie habe ich gerade einen Knoten im Kopf. 

1. 
Wir instanzieren 'Game' und erzeugen im __init__ das 'Board' Objekt.
Müssen wir nicht dort dann die 24 Felder instanzieren mit ihren std. Werten (inner,outer,mid, owner:none etc.)? 
Da fehlt für mich eine Funktion init_fields(), oder nehmen wir dafür ein Dictionary? 
{ 'inner' : ['None, None, None, None, None, None, None, None],
'outer' : ['None, None, None, None, None, None, None, None],
'mid' : ['None, None, None, None, None, None, None, None],
}
So brauchen wir keine extra Klasse dafür...

move_piece() wird dann mit der Information aus der GUI gefüttert. 
Bsp.: (Spieler zieht 'outer' Spielstein Position 3 auf 'mid' Position 3) -> 
fields['outer'][position] = 'None' ; fields['inner'][position] = owner
vorher natürlich prüfen ob der move valid ist -> änderungen eintragen oder exception 

2. 
Was machen wir mit den Rückgabewerten der Spielsteine  'Player'.make_move(func)
Kann es sein, dass du dir vorgestellt hast die Rückgabewerte an die GUI weiterzureichen?
Ansonsten könnten wir in Board die get_all_fields(player=None) erweitern.
Wenn kein Spieler angegeben ist, holt er alle freien Felder ansonsten halt Spieler spezifisch.
Dadurch könnte die GUI auch auf eine Änderung reagieren oder wäre das zu umständlich?

3.
move_piece müssten wir erweitern für den Fall, dass jemand mithilfe der Mühle einen gegnerischen Spielstein löscht. 
also move_piece(player, new_field=None, old_field=None) -> aber mit der Bedingung, dass nur ein Feld der beiden auf None stehen darf, ansonsten Exception.
new_field = None -> löschen eines Steines
old_field = None -> setzen eines Steines
beide gefüllt -> Stein wird bewegt

Mehr fällt mir Heute nicht mehr ein.

**Comment by ghost** [comment]
> Müssen wir nicht dort dann die 24 Felder instanzieren mit ihren std. Werten (inner,outer,mid, owner:none etc.)?

Wozu instanzieren? Wenn die Felder "none" sind, können sie jederzeit von player1 und player2 verwendet werden. Ich hätte für die einzelnen Felder zuerst an ein namedtuple gedacht, dass dann am Objekt des Boards hängt, somit 'weiß' man dann, welcher Spieler Steine auf den einzelnen Feldern hat.

Ich bin mit dem UML-Design nicht firm, was bedeuten gefüllte Kreise und leere? Was bedeuten die Pfeile? (Komposition, Aggegation, Vererbung usw. usf.?)

**Comment by ghost** [comment]
Ich weiß nicht wie sinnvoll das ist, was ich oben geschrieben habe. Ich versuche es mal im Code darzustellen: 
```python
from collections import namedtuple
Field = namedtuple('Field', 'square_name index owner')
 
class Board:
 
    def get_all_fields(self):
        fields = []
        for index in range(0, 8, 1):
            for square in 'inner', 'mid', 'outer':
                fields.append(Field(square, index, None)
        return fields
```

get_all_fields() würde so allerdings immer ein leeres Board erzeugen, mit der 'fields' könnte man dann allerdings nach und nach die owner ersetzen. 

EDIT: kann leider nicht funktionieren, da namedtuples immutable sind.

**Comment by seblin** [comment]
Habe mal die Vorschläge von @sebastian2443 mit aufgenommen. Außerdem habe ich das mit den Callbacks etwas umgestellt. Die sind dazu gedacht, dass man die Logik mit beliebigen Oberflächen benutzen kann (z.B. mit der GUI von Qt) ohne zu große Kenntnisse für die Logik haben zu müssen. Um beim Beispiel zu bleiben: Die GUI müsste eine Funktion zum Erzeugen der Spieler (Abfrage von Name und Farbe) sowie eine für das Entgegennehmen des Resultats am Ende des Spiels übergeben. Die Spieler bekommen bei ihrer Erzeugung außerdem einen Callback für die Abfrage des nächsten Zuges mit. Von da an müsste man nur noch game.play() oder sowas aufrufen und die Logik würde komplett übernehmen. Immer wenn Interaktion mit dem Benutzer mittels GUI nötig ist, wird einfach der vordefinierte Callback aufgerufen.

Hier nun das neue Diagramm:
![muehle](https://user-images.githubusercontent.com/621748/34840656-f20a5a04-f705-11e7-9363-6c95619b7a5a.png)

**Comment by seblin** [comment]
@sls89 
Leere Keise sind Attribute, gefüllte Kreise sind Methoden. Die eingekreisten C's im oberen Teil der Boxen zeigen an, dass es Klassen sind. 

Die Pfeilverbindungen habe ich gemacht, um die Abhängigkeiten zu verdeutlichen: Game kennt Player und Board. Player und Board kennen sich gegenseitig. Board und Field kennen sich auch gegenseitig. Von Game weiß keiner der Drei etwas.

Deinen Quellcode möchtest du vielleicht nochmal auslagern oder neu formatieren, da er schwer lesbar ist.

**Comment by seblin** [comment]
Hier noch ein paar kleine Detailänderungen an der API. Die Pfeile habe ich jetzt weg gelassen, weil es dann übersichtlicher ist.
![muehle](https://user-images.githubusercontent.com/621748/34841525-d3545382-f708-11e7-89f7-7f0096ab97fe.png)
(und sorry für den Triple Post...)

**Comment by ghost** [comment]
@seblin Danke für die Erläuterung. An der Stelle der Kreise stehen "normalerweise" ja die Zugriffsmodifizierer - eigentlich wird ja deutlich dass Methoden immer "im untersten Kästchen", Attribute zwischen Klassennamen und Methoden, angezeigt werden. Aber jetzt weiß ich zumindest wie das hier gemeint ist. 

Wie gesagt, meine Idee wird ohne irgenwie in die Richtung zu gehen eine __new__() Methode zu implementieren nix, da namedtuples immutable sind.

**Comment by seblin** [comment]
@sls89 
Deine Anmerkung zu den Felder verstehe ich nicht so ganz, denn was du beschreibst, haben wir doch fast genau so vor, nur halt in ein Dict gesteckt anstatt in eine Liste.

Ich würde ebenfalls ein namedtuple verwenden wollen:
```python
class Field(namedtuple('Field', 'square_name, index, owner')):
    def __new__(cls, square_name, index, owner=None):
        if square_name not in {'inner', 'mid', 'outer'}:
            raise ValueError('Invalid square name')
        if not 0 <= index <= 7:
            raise ValueError('Field index out of range')
        return tuple.__new__(cls, (square_name, index, owner))
```

**Comment by ghost** [comment]
Ich stehe gerade etwas im Dunkeln, weil ich nicht weiß wie über Field der owner gesetzt werden soll.

**Comment by seblin** [comment]
Das ist mir gerade auch schon aufgefallen. Entweder indem man ein neues Feld erzeugt (was IMHO komisch wäre) oder indem man doch kein namedtuple verwendet. Oder man lässt den owner an der Stelle weg und regelt das anders.

EDIT: Man könnte z.B. die belegten Felder an den jeweiligen Spieler binden. Dann wird der owner darüber ermittelt. Das Feld würde davon nichts mitkriegen und könnte den ganzen Spielverlauf über unveränderbar bleiben. In move_piece() wird ja sowieso der Spieler übergeben.

**Comment by ghost** [comment]
Eine Alternative wäre, das Spielfeld zu erstellen, und anschließend dem jeweiligen Spieler die namedtuple zu zuordnen. Dadurch könnte auch der Ansatz weiter verfolgt werden, dass der Spieler "weiß", ob noch Spielzüge möglich sind, oder er ggf. durch die bestehenden namedtuple eine Mühle erspielt hat. 

```python
from collections import namedtuple
Field = namedtuple('Field', 'square_name index owner')
  
class Board:
 
    def get_all_fields(self):
        fields = []
        for index in range(0, 8, 1):
            for square in 'inner', 'mid', 'outer':
                fields.append(Field(square, index, None))
        return fields

obj = Board()
get_fields = obj.get_all_fields()
player1_pieces = get_fields[3]._replace(owner="Hans")
print(player1_pieces)

**Comment by seblin** [comment]
Hab's umgeschrieben:
![muehle](https://user-images.githubusercontent.com/621748/34844848-171aa030-f713-11e7-99b6-4d2dd82ec5a0.png)

Der Code zum Erhalten des Besitzers wäre dadurch noch recht trivial:
```python
def get_owner(self, field):
    for player in self.players:
        if field in player.assigned_fields:
            return player
```
Was noch durchdacht werden müsste, ist wie das Board an die beiden Spieler gebunden werden soll. Aber das könnt ihr beide etzt auch mal machen... :D

**Comment by seblin** [comment]
@sls89 
Stimmt, an _replace() hatte ich gar nicht gedacht. Das geht natürlich auch.

**Comment by ghost** [comment]
> Was noch durchdacht werden müsste, ist wie das Board an die beiden Spieler gebunden werden soll. Aber das könnt ihr beide etzt auch mal machen... :D

Da würde ich wohl einen Container bauen, der alle 24 Spielfelder führt und überprüft ob Mühlen vorhanden sind und ob noch Spielzüge möglich sind. Dann würde ich das auch nicht unbedingt an ein jeweiliges Spieler-Objekt binden. Dafür haben wir ja das owner-Attribut.

**Comment by seblin** [comment]
Das Erzeugen der Felder ist in Python übrigens ein Einzeiler:
`[Field(name, i) for name in ('inner', 'mid', 'outer') for i in range(8)]`

**Comment by ghost** [comment]
@seblin Möchtest du das UML so lassen?

Meine Idee wäre, dass wir ruhig Field aus square_name, index und owner / player bestehen lassen. Somit wären die Methoden get_owner() und get_neighbour_fields() obsolete, denn in Board könnte fields Dreh- und Angelpunkt sein. fields kann das ganze Spielfeld repräsentieren, und nach jedem Spielzug durch move_piece() könnte is_in_mill() eine mögliche Mühle auf Grundlage von fields prüfen. Das Ergebnis wird dann z.B. an Game zurückgeliefert. 

Somit wären dann auch die beiden Spieler player1 und player2 mit untrennbar verbunden, da Board diese Objekte kennt und alle zugehörigen Steine zuordnen kann.

**Comment by seblin** [comment]
get_neighbour_fields() ist eigentlich so gedacht, dass man für einen Stein direkt alle erlaubten Felder bekommt, wo er hin darf. Wahrscheinlich sollte man das besser als get_allowed_fields(piece) schreiben. Dazu müsste man es nochmal umschreiben, sodass man eine Klasse namens Piece hätte, für die eine Farbe (Besitzer bzw. Spieler) sowie ein Feld (oder None, falls der Stein noch nicht gesetzt wurde) zugeordnet sind. Was haltet ihr davon?

**Comment by sebastian2443** [comment]
Wir können gerne namedtuple nutzen.

Ich würde bei der Erstellung des Boards auch alle 24 Felder vorweg mit owner=None generieren lassen.
Dann sparen wir uns die Prüfung ob das Feld schon generiert wurde. 

Muss die Klasse Player denn Wissen welche Felder dem Spieler gehören?
Die Info brauch doch nur die GUI und die kann sich die Info vom Board holen mittels get_all_fields(owner)
Der reelle Spieler sieht doch anhand der Farbe was ihm gehört.
Und fehlerhafte Spielzüge oder nicht zugehörige Spielsteine werden eh auf validität geprüft. 

Das könnte so aussehen (ohne valide Prüfungen):
```python
from collections import namedtuple

class Field(namedtuple('Field', 'square_name index owner')):
    def __eq__(self, other):
        if self.square_name == other.square_name and self.index == other.index:
            return True
        return False
 
class Board(object):
    def __init__(self):
        self.fields = [Field(name, i, None) for name in ('inner', 'mid', 'outer') for i in range(8)]
    
    def get_all_fields(self, player=None):
        return [field for field in self.fields if field.owner == player]

    def move_piece(self, old_field=None, new_field=None):
        for field in self.fields:
            if field == new_field and field.owner == None:
                index = self.fields.index(field)
                self.fields[index] = new_field

class Player(object):
    def __init__(self, name, board):
        self.name = name
        self.board = board
    
    def make_move(self, old_field, new_field):
        self.board.move_piece(old_field, new_field)
    
    def fields(self):
        return self.board.get_all_fields(self.name)

board = Board()
player_1 = Player('Peter', board)
print(player_1.fields())
player_1.make_move(None, Field('outer', 2, 'Peter'))
print(player_1.fields())
```

get_neighbour_fields /get_allowed_fields / valid_moves brauchen wir. 
Wie willst du sonst ermitteln, ob der Spieler sein Stein auf ein Nachbarfeld zieht oder nicht einfach eins überspringt? Wir müssen wissen welche Felder begehbar sind für den jeweils ausgewählten Spielstein.
Wir müssen sogar jede Runde herausfinden, ob der Spieler überhaupt einen Spielstein bewegen kann.

Dann hätten wir 18 Piece Objekte und 24 Fields Objekte. Die Piece Objekte sind dann in 'Player' gespeichert und die Fields im 'Board'. Haben wir dadurch einen mehrwert? Die Spielsteine sind alle gleich und unterscheiden sich nur durch ihren Besitzer. Andererseits kann einem Spieler nur ein Spielstein gehören und kein Feld. 

Wie wir is_in_mill() / valid_mill() umsetzen wollen ist mir bisher unklar. alle theoretischen Kombinationen speichern und schauen ob eins zutrifft?

**Comment by seblin** [comment]
Hier ein neuer Vorschlag:
![muehle](https://user-images.githubusercontent.com/621748/34884807-3452d16c-f7be-11e7-9095-2278bec931e0.png)
Das Board wird durch Game erzeugt und direkt an den jeweiligen Spieler übergeben. Die Felder haben wieder ihren Owner. Abfrage der Spieler und Spielzüge sowie Bekanntgabe des Endergebnis erfolgt über Methoden, die zum Überschreiben gedacht sind. Einerseits hat man mit Game jetzt so eine Art Gottklasse, aber ich denke das hält sich im Rahmen. Zudem wurde mir mein vorheriges Diagramm zu kompliziert.

**Comment by ghost** [comment]
Wenn ich mich nicht verzählt habe, gibt es für eine erste, einfache Mühle um die 20 Möglichkeiten, daher fände ich es ziemlich overkill alle Möglichkeiten abzubilden und dann in is_in_mill() gegen zu prüfen. 

Ich hätte mir so etwas in der Art (stark vereinfachtes Beispiel) überlegt:

```python
"""
0-----------1-----------2
|           |           |
|   0-------1-------2   |
|   |       |       |   |
|   |   0---1---2   |   |
|   |   |       |   |   |
7---7---7       3---3---3
|   |   |       |   |   |
|   |   6---5---4   |   |
|   |       |       |   |
|   6-------5-------4   |
|           |           |
6-----------5-----------4                        
"""

from collections import namedtuple

Field = namedtuple('Field', 'square_name index owner')

class Board:

    def get_all_fields(self):
        return [Field(name, i, None) for name in ('inner', 'mid', 'outer') for i in range(8)]

    def is_in_mill(self, fields):
        intervall = 0
        for field in fields:
            if 'inner' in field:
                if fields[intervall].owner == 'Hans' and fields[intervall+1].owner == 'Hans' \
                        and fields[intervall+2].owner == 'Hans':
                    print("Mühle!")
            intervall += 2

board = Board()
fields = board.get_all_fields()
# Set owner Hans for field index 0, 1 and 2
field_update = fields[0]._replace(owner="Hans")
fields[0] = field_update
fields[1] = field_update
fields[2] = field_update
board.is_in_mill(fields)
```
so könnte man über 'inner', 'mid' und 'outer' iterieren und über das Intervall die Kombinationen steuern (Feld 0 - 2, 2-4, 4-6 usw.) - wie gesagt, da gehört noch Optimierung hinein und auch ob man die Abfrage if 'inner' machen muss, sei mal dahingestellt. Man müsste das dann nur noch um die Diagonalen und von 'inner' nach 'outer' prüfen, z.B. 2-2-2 oder 3-3-3. Evtl. kann man alle drei Felder einer potentiellen Mühle auch mittels zip() zusammenführen und den owner prüfen. Dann spart man sich die o.g. if Abfrage in der Form. 

Ich habe mit meinem namedtuple weiter programmiert, aber nur zur Einfachheit. Mit den bisherigen Vorschlägen bin ich d'accord. 

~~EDIT: wie wäre es, wenn wir evtl. 'inner', 'mid' und 'outer' auflösen und direkt mit den Indizes arbeiten? Mit dem namedtuple können wir das sehr schön abbilden.~~

@sebastian2443: bitte nicht von meinem Code verwirren lassen, Fokus soll hier nur auf is_in_mill() liegen, den Rest können wir gerne wie in deinem Beispiel mit Board.__init__() usw. machen. 

EDIT2: 

> get_neighbour_fields /get_allowed_fields / valid_moves brauchen wir.
Wie willst du sonst ermitteln, ob der Spieler sein Stein auf ein Nachbarfeld zieht oder nicht einfach eins überspringt? 

In make_move() reicht eine einfache Anweisung auf, ob der Field.owner != None ist und wir nicht selber bereits einen Stein auf diesem Feld liegen haben. Dazu brauchen wir eig. keine weitere Methode.

**Comment by seblin** [comment]
is_in_mill() hast du wohl etwas falsch verstanden. Es wird nur geprüft, ob ein bestimmtes Feld (mit Stein) Teil einer Mühle ist. Dazu muss man nicht alle Felder durchlaufen, sondern lediglich prüfen ob rechts und links sowie oben und unten davon Steine gesetzt sind. Also es geht nicht darum, alle denkbaren Mühlen anzuzeigen. Vielmehr soll hier nach Anforderung eines Spielzugs nachgeschaut werden ob der Stein in eine Mühle gesetzt wurde.

EDIT: Daher steht da auch field und nicht fieldS. ;)

**Comment by ghost** [comment]
@seblin oh, ok. Das klingt für mich allerdings etwas komplizierter. Für mich war die Vorstellung einfacher, dass an zentraler Stelle ein komplettes Spielfeld (nicht einzelne Felder) existiert an welchem geprüft wird, wo wer Steine liegen hat, und ob sich aus diesen Kombinationen nach jedem Spielzug eine Mühle ergibt.

**Comment by seblin** [comment]
Ist ja auch so, denn das Board, mit dem interagiert wird, kennt ja seine Feldbelegung.

**Comment by ghost** [comment]
@seblin Ach herrje. Ich hätte mehr auf die Deutung der Methode is_in_mill() achten sollen. Danke für die Aufklärung.

**Comment by seblin** [comment]
Ungetestet:
```python
SQUARE_NAMES = ('inner', 'mid', 'outer')

def is_in_mill(self, field):
    square_fields = self.fields[field.square_name]
    player = field.player
    if (field.index % 2) == 0:
        candidates = [
            [square_fields[(field.index + i) % 8] for i in (0, 1, 2)],
            [square_fields[(field.index - i) % 8] for i in (0, 1, 2)]
        ]
    else:
        candidates = [
            [self.fields[square][field.index] for square in SQUARE_NAMES],
            [square_fields[(field.index + i) % 8] for i in (-1, 0, 1)]
        ]
    for candidate in candidates:
        if all(field.player == player for field in candidate):
            return True
    return False
```

**Comment by ghost** [comment]
@seblin mal 'ne kurze Statusabfrage: können wir sebastian's letzten Code-Vorschlag verwenden? Ich würde den Code gerne mal zum Testen bei mir hernehmen und schauen, dass ich das alles kapiere. Ich merke gerade, dass mir das UML hier den Arsch rettet weil es doch etwas Zeit brauch um im Code zu erkennen wer wann mit wem wo herummacht.

**Comment by seblin** [comment]
Wobei sein Codevorschlag nicht mehr dem aktuellen UML-Diagramm entspricht. Sind mit meinem letzten Vorschlag denn alle einverstanden?

**Comment by ghost** [comment]
Ja.

**Comment by seblin** [comment]
Wir sollten natürlich noch die Meinung von @sebastian2443 abwarten. Habe jedenfalls eine Überarbeitung von seinem Code-Vorschlag soeben in Issue #2 gestellt.

**Comment by sebastian2443** [comment]
Ich finde den letzten Vorschlag gut! Dann wäre der Issue #1 abgeschlossen damit. 

make_move() reicht die Koordinaten an Board weiter.
Solange die Spieler ihre 9 Spielsteine noch setzen, muss der Eigentümer des Feldes None sein.
Aber sobald die Spieler ihre Spielsteine auf dem Feld ziehen/bewegen, muss geprüft werden ob die Bewegung auf ein Nachbarfeld des Spielsteines folgt und der Eigentümer None ist. Sonst kann der Spieler ja Felder überspringen. 

Eine Mühle ist doch nur dann gültig, wenn sie das erste Mal erzeugt wurde. Daher bietet sich an immer nach erfolgreicher Umsetzung eines Spielsteines seine Nachbarfelder auf eine gültige Mühle zu prüfen. 
Egal wo der Spielstein gesetzt wird, es betrifft immer zwei Reihen. Wir ermitteln diese und gleichen das mit dem Mühlen-Katalog ab und prüfen dann auf Eigentümer. Voila.
Ob wir alle Möglichkeiten in ein DICT hinterlegen oder eine kleine Methode dafür schreiben, können wir uns offen halten.

**Comment by seblin** [comment]
Alles klar, dann mach ich den Issue hiermit zu.
